owner: high-performance-analytics
repo: hpa-uptime

sites:

  - name: WISE [Frontend]
    slug: wise-frontend
    url: https://wise.hpa.ai
    method: GET
    followRedirects: true
    maxRedirects: 2
    headers:
      - "User-Agent: Mozilla/5.0"

  - name: WISE [Backend]
    slug: wise-backend
    url: https://wise-api.hpa.ai/hally/health
    icon: https://wise.hpa.ai/favicon.ico
    method: GET
    followRedirects: true
    maxRedirects: 2
    headers:
      - "User-Agent: Mozilla/5.0"
  
  - name: HIVE Waste [Frontend]
    slug: hive-waste-frontend
    url: https://hivewaste.hpa.ai
    icon: https://hivewaste.hpa.ai/favicon.ico
    method: GET
    followRedirects: true
    maxRedirects: 2
    headers:
      - "User-Agent: Mozilla/5.0"
    
  - name: HIVE Waste [Backend]
    slug: hive-waste-backend
    url: https://hivewaste-api.hpa.ai/health/
    icon: https://hivewaste.hpa.ai/favicon.ico
    method: GET
    followRedirects: true
    maxRedirects: 2
    headers:
      - "User-Agent: Mozilla/5.0"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.hpa.ai # TODO custom domain: uncomment
  baseUrl: /hpa-uptime
  logoUrl: https://hpa.ai/wp-content/themes/wptheme/img/HPA-mathtoinnovate.svg
  name: HPA Uptime Monitor
  introTitle: "**HPA services status and uptime dashboard**"
  introMessage: This dashboard shows the real-time availability of HPA services.
  links:
  - rel: stylesheet
    href: https://high-performance-analytics.github.io/hpa-uptime/custom.css # TODO custom domain: change domain
  favicon: https://www.hpa.ai/wp-content/uploads/2023/07/cropped-hpa-favicon-32x32.png
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# Custom schedule for GitHub Actions
workflowSchedule:
  uptime: "*/30 * * * *"       # ← every 30 minutes
  graphs: "0 0 * * *"          # default: once a day at midnight
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
