name: Remove Status Label on Close

on:
  issues:
    types: [closed]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove "status" label on closed issues
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const statusLabel = issue.labels.find(label => label.name === "status");
            if (statusLabel) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                name: "status"
              });
            }
